"""
geophis: Wrapper simple sobre geopandas/shapely para tareas de SIG.

La idea es que operaciones comunes (cargar, recortar, disolver, buffer,
fusionar, guardar...) se llamen con una sola función en español, sin
tener que recordar la sintaxis de geopandas cada vez.

Uso rápido:

    import geophis as geo

    ejido = geo.cargar("ejido.shp")
    hidro = geo.cargar("hidrologia.shp")

    hidro = geo.reproyectar(hidro, 32613)
    hidro = geo.recortar(hidro, ejido)
    hidro = geo.disolver(hidro)
    hidro = geo.zona_de_influencia(hidro, 20)
    geo.guardar(hidro, "salida.shp")
"""

from .archivo import (
    cargar,
    cargar_puntos,
    guardar,
    comprobar_nombres_shp,
    exportar_tabla,
    convertir,
    cargar_waypoints,
    cargar_tracks,
    detectar_utm,
    detectar_cota,
    detectar_campo,
    listar_capas,
    describir,
)
from .tabla import (
    seleccionar_por_atributo,
    seleccionar_por_ubicacion,
    estadisticas_de_resumen,
    unir_campo,
    atributos_a_mayusculas,
    atributos_a_minusculas,
    listar_campos,
    agregar_campo,
    calcular_campo,
    renombrar_campos,
    eliminar_campos,
    conservar_campos,
    ordenar_campos,
    cambiar_tipo,
    reemplazar_valores,
    ordenar_filas,
    crear_capa,
)
from .proyeccion import reproyectar
from .geometria import (
    nombre_campo_libre,
    recortar,
    disolver,
    disolver_por_grupo,
    separar_multipartes,
    zona_de_influencia,
    puntos_a_linea,
    puntos_a_poligono,
    linea_a_poligono,
    borrar,
    resolver_por_prioridad,
    repartir_por_cercania,
    fusionar,
    crear_cuadro,
    cuadros_mde,
    limpiar_vacias,
    reparar_geometrias,
    calcular_superficie,
    superficie_total,
    superficie_total_ha,
    comprobar_particion,
    longitud_total,
    longitud_total_m,
    concordancia_lineas,
    bloques_ajedrez,
    pendiente_sostenida,
    sostenimiento_por_clase,
    ancho_banda,
    separacion_media,
    auditar_rangos,
    intersecar,
    union_espacial,
    entidad_a_punto,
    cercano,
    puntos_sobre_linea,
    identidad,
    union,
    thiessen,
    partir_por_linea,
    calcular_longitud,
    calcular_coordenadas,
    medir_geodesico,
    simplificar,
    cerrar_microhuecos,
    rellenar_huecos,
    subdividir_por_area,
    eliminar_menores,
    ruta_red,
    isocronas,
)
from .raster import (
    cargar_raster,
    cargar_bandas,
    guardar_raster,
    recortar_raster,
    mosaico,
    rellenar_nodata,
    mascara_relleno,
    remuestrear,
    reproyectar_raster,
    indice_vegetacion,
    interpolar_mde,
    planos_de_curva,
    cotas_por_cruce,
    validar_mde,
    extraer_valores,
    rasterizar,
    combinar_categorias,
    poligonizar,
    limpiar_moteado,
    calcular_orientacion,
    calcular_pendiente,
    ruta_a_pie,
    ruta_costo_minimo,
    reclasificar_rangos,
    sombreado,
    resumen_raster,
    estadisticas_zonales,
    alinear_rasters,
    curvas_de_nivel,
    vista_previa,
)
from .hidrologia import (
    quemar_cauces,
    acondicionar_mde,
    acumulacion_flujo,
    rellenar_sumideros,
    altura_sobre_cauce,
    etiquetar_laderas,
    red_drenaje,
    orden_cauces,
    delimitar_cuenca,
    microcuencas,
)
from .satelite import buscar_sentinel2, imagen_sentinel2
from .zonas import zonificar
from .metrologia import (
    resolucion_regla,
    min_pixeles_umm,
    umbral_celdas,
    tolerancia_rasterizacion_ha,
    margen_borde_celdas,
)
from .barridos import (
    barrer_resolucion,
    barrer_vecinos,
    raster_distancia,
    separaciones,
    histograma_fase,
    amplitud_rizo,
    juzgar_clasificaciones,
)
from .parametros import (
    derivar_parametros,
    tabla_procedencia,
    sin_medir,
    comprobar_cifras_firmes,
)

__all__ = [
    # archivo
    "cargar",
    "cargar_puntos",
    "guardar",
    "comprobar_nombres_shp",
    "exportar_tabla",
    "convertir",
    "cargar_waypoints",
    "cargar_tracks",
    "detectar_utm",
    "detectar_cota",
    "detectar_campo",
    "listar_capas",
    "describir",
    # tabla
    "seleccionar_por_atributo",
    "seleccionar_por_ubicacion",
    "estadisticas_de_resumen",
    "unir_campo",
    "atributos_a_mayusculas",
    "atributos_a_minusculas",
    "listar_campos",
    "agregar_campo",
    "calcular_campo",
    "renombrar_campos",
    "eliminar_campos",
    "conservar_campos",
    "ordenar_campos",
    "cambiar_tipo",
    "reemplazar_valores",
    "ordenar_filas",
    "crear_capa",
    # proyeccion
    "reproyectar",
    # geometria
    "nombre_campo_libre",
    "recortar",
    "disolver",
    "disolver_por_grupo",
    "separar_multipartes",
    "zona_de_influencia",
    "puntos_a_linea",
    "puntos_a_poligono",
    "linea_a_poligono",
    "borrar",
    "resolver_por_prioridad",
    "repartir_por_cercania",
    "fusionar",
    "crear_cuadro",
    "cuadros_mde",
    "limpiar_vacias",
    "reparar_geometrias",
    "calcular_superficie",
    "superficie_total",
    "superficie_total_ha",
    "comprobar_particion",
    "longitud_total",
    "longitud_total_m",
    "concordancia_lineas",
    "bloques_ajedrez",
    "pendiente_sostenida",
    "sostenimiento_por_clase",
    "ancho_banda",
    "separacion_media",
    "auditar_rangos",
    "intersecar",
    "union_espacial",
    "entidad_a_punto",
    "cercano",
    "puntos_sobre_linea",
    "identidad",
    "union",
    "thiessen",
    "partir_por_linea",
    "calcular_longitud",
    "calcular_coordenadas",
    "medir_geodesico",
    "simplificar",
    "cerrar_microhuecos",
    "rellenar_huecos",
    "subdividir_por_area",
    "eliminar_menores",
    "ruta_red",
    "isocronas",
    # raster / hidrologia / satelite / metrologia / barridos
    "cargar_raster",
    "cargar_bandas",
    "guardar_raster",
    "recortar_raster",
    "mosaico",
    "rellenar_nodata",
    "mascara_relleno",
    "remuestrear",
    "reproyectar_raster",
    "indice_vegetacion",
    "interpolar_mde",
    "planos_de_curva",
    "cotas_por_cruce",
    "validar_mde",
    "extraer_valores",
    "rasterizar",
    "quemar_cauces",
    "combinar_categorias",
    "poligonizar",
    "limpiar_moteado",
    "acondicionar_mde",
    "acumulacion_flujo",
    "rellenar_sumideros",
    "altura_sobre_cauce",
    "etiquetar_laderas",
    "red_drenaje",
    "orden_cauces",
    "delimitar_cuenca",
    "microcuencas",
    "buscar_sentinel2",
    "imagen_sentinel2",
    "calcular_orientacion",
    "calcular_pendiente",
    "ruta_a_pie",
    "ruta_costo_minimo",
    "reclasificar_rangos",
    "sombreado",
    "resumen_raster",
    "estadisticas_zonales",
    "alinear_rasters",
    "curvas_de_nivel",
    "vista_previa",
    "resolucion_regla",
    "zonificar",
    "barrer_resolucion",
    "barrer_vecinos",
    "min_pixeles_umm",
    "umbral_celdas",
    "tolerancia_rasterizacion_ha",
    "margen_borde_celdas",
    "raster_distancia",
    "separaciones",
    "histograma_fase",
    "amplitud_rizo",
    "juzgar_clasificaciones",
    # parametros
    "derivar_parametros",
    "tabla_procedencia",
    "sin_medir",
    "comprobar_cifras_firmes",
]

# Los reportes de consola de todas las funciones. `geo.MOSTRAR = False` los calla;
# los avisos de defecto salen igual.
MOSTRAR = True

__version__ = "1.1.0"
